### ISSUE TITLE
Any interest in incorporating Scanamo instead of the Java DynamoDB library

### ISSUE THREAD

**Issue by calvinlfer** [dnvriend/sam-dynamodb-seed.g8#1]
Guardian's Scanamo provides a much nicer API for interacting with DynamoDB, just wanted to see whether there was any interest in incorporating this?

**Comment by dnvriend** [comment]
Hi @calvinlfer Great idea, I like the scanamo abstraction as well. To support developers with both, I've created a new seed that you can use [sam-dynamodb-scanamo-seed.g8](https://github.com/dnvriend/sam-dynamodb-scanamo-seed.g8). Have a go at it. We're still working on the [sbt-sam](https://github.com/dnvriend/sbt-sam), plugin to let it help us create serverless components. Let me know what you think and spread the word!

**Comment by calvinlfer** [comment]
Sounds great!
